apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zoqxwir1x-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:06ad0d7cb9a034247a16fc304307c79ee4318adf@sha256:c7bcd23d8f6148727f4fa1784f127f84d9395697ef58277e38f17021948f1b86
          name: container-image
